### ISSUE TITLE
@default([]) will crash the generator

### ISSUE THREAD

**Issue by KuhlTime** [pantharshit00/prisma-docs-generator#68]
First of all thanks for your amazing work! 🫶

Once you have time maybe you can take a look at the `@default([])` attribute. The generator seems to crash for me everytime I am enabling it. This is the prisma Schema that I used:

```prisma
model Person {
  id			String		@id @db.Uuid
  first_name	String		@db.VarChar(50)
  last_name		String		@db.VarChar(50)
  emails		String[]	@default([]) @db.VarChar(320)

  @@map("person")
}
```

Here is the error log from what Prisma outputted running `pnpx prisma generate`.

<details>
<summary>Error Log</summary>

```
> prisma generate

  prisma:engines  binaries to download libquery-engine, migration-engine +0ms
  prisma:loadEnv  project root found at ./package.json +0ms
  prisma:tryLoadEnv  Environment variables loaded from ./.env +0ms
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
  prisma:getConfig  Using getConfig Wasm +0ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +2ms
  prisma:getDMMF  Using getDmmf Wasm +0ms
  prisma:getDMMF  Using given datamodel +0ms
  prisma:getDMMF  dmmf data retrieved without errors in getDmmf Wasm +29ms
  prisma:generator  prismaCLIDir./node_modules/prisma +0ms
  prisma:generator  prismaClientDir ./node_modules/@prisma/client +0ms
  prisma:generator  baseDir ./prisma +0ms
  prisma:generator  typescriptPath ./node_modules/.pnpm/typescript@5.0.3/node_modules/typescript +1ms
  prisma:GeneratorProcess  2023-04-06T15:40:51.169Z prisma:client:generator  requiredEngine: libqueryEngine +0ms
  prisma:getGenerators  neededVersions {
  "659ef412370fa3b41cd7bf6e94587c1dfb7f67e7": {
    "engines": [
      "libqueryEngine"
    ],
    "binaryTargets": []
  }
} +0ms
  prisma:getGenerators  {
  generatorBinaryPaths: {
    libqueryEngine: {
      'darwin-arm64': './node_modules/.pnpm/prisma@4.12.0/node_modules/prisma/libquery_engine-darwin-arm64.dylib.node'
    }
  }
} +25ms
  prisma:GeneratorProcess  2023-04-06T15:40:51.229Z prisma:loadEnv  project root found at ./package.json +58ms
  prisma:GeneratorProcess  Error: unable to write files for Prisma Docs Generator +83ms
Error: Error: 
✔ Generated Prisma Client (4.12.0 | library) to ./node_modules/.pnpm/@prisma+client@4.12.0_prisma@4.12.0/node_modules/@prisma/client in 83ms

Cannot read properties of undefined (reading 'join')
    at _Generate.parse (./node_modules/.pnpm/prisma@4.12.0/node_modules/prisma/build/index.js:101892:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (./node_modules/.pnpm/prisma@4.12.0/node_modules/prisma/build/index.js:103530:18)
```

</details>

Environment:

- OS: `macOS 13.1 (22C65)`
- node.js: `v19.3.0`
- Prisma: `v4.12.0`
- primsa-docs-generator: `v0.6.0`

**Comment by KuhlTime** [comment]
Amazing thank you so much @pantharshit00
